[package]
name = "drng"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "drng"

[examples]
example0 = "examples/example0.rs"

[dependencies]
